### ISSUE TITLE
Supply Dockerfile on standard input

### ISSUE THREAD

**Issue by lassik** [jessfraz/dockfmt#7]
Would you accept a feature whereby a Dockerfile can optionally be read from standard input instead of reading it from a file? I'd like to write editor integrations for the `dockfmt fmt` subcommand. It would be great to be able to do something like `dockfmt fmt -` or just `dockfmt fmt` (compare to `gofmt` with no arguments) to format a file in a text editor. This can already be done on many (most?) Unix systems with `dockfmt fmt /dev/stdin` but that's not as portable.

I can make a PR about this if it helps.

**Comment by jessfraz** [comment]
yes totally :)

**Comment by jessfraz** [comment]
closed via #8
